
services:
  basic_db:
    image: mongo:latest
    container_name: basic_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27018:27017"

  basic_be:
    working_dir: /app
    container_name: basic_be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - basic_db
    env_file:
      - .env
    command: ["npm", "run", "start"]

    